### ISSUE TITLE
Move "People" app to "Circles"

### ISSUE THREAD

**Issue by brylie** [CompanionshipCare/companionship-care#141]
Currently, users can log in and add a "Person" and then add companions for that person. However, it may be more natural to think of adding a "Circle" and inviting companions to join that group rather than "joining a person." While the phrase "care group" would be somewhat familiar, using "care circle" more closely implies the relationship of the group to a central person -- or person-centric care.

## Task

- [ ] determine how to "rename" or "move" the People app to be called Circles
- [ ] ensure that all data are preserved via migrations
- [ ] ensure that the People app is either renamed or removed without issue

## Resources

- https://docs.djangoproject.com/en/4.1/topics/migrations/#data-migrations
- https://stackoverflow.com/a/64133141
