### ISSUE TITLE
Create use case document with user journey diagrams

### ISSUE THREAD

**Issue by brylie** [CompanionshipCare/companionship-care#206]
There are a few key use cases for the Companionship Care app. Let's clarify those use cases with brief descriptions and user journey diagrams. Make sure the use cases build upon our user personas, adding new personas as needed.

```[tasklist]
### Tasks
- [ ] Identify key [use cases](https://en.wikipedia.org/wiki/Use_case)
- [ ] Identify key role(s) for each use case
- [ ] Make sure each role has a corresponding [User Persona](https://www.hotjar.com/blog/user-personas/)
- [ ] Write a brief description for each use case
- [ ] Add a [user journey diagram](https://mermaid.js.org/syntax/userJourney.html) for each use case
```

**Comment by brylie** [comment]
@werberger, would you like to take this issue? It will help clarify the scope and goals of this project. No code is necessary, other than some markdown with mermaid diagrams.

**Comment by werberger** [comment]
Yeah, happy to give it a go @brylie

**Comment by brylie** [comment]
Great! Let me know if I've left out any key context. Just know that I don't have all of the answers for specific use cases, since this app is growing organically. So, your intuition is valuable here.

**Comment by brylie** [comment]
Also, keep in mind that the Companionship Care users (Care Coordinators and Companions) may be different people than the main care recipients, such as people living independently who are in need of companionship. So, some of our current personas may not use the app directly, but may benefit indirectly through companionship that is coordinated via the app.

As an aside, I'm trying to find simple, non-patronizing terms to describe the various people and roles for whom we are designing, so any assistance with improved wording is greatly appreciated.

**Comment by werberger** [comment]
Thanks for pointing out. I'm not sure I'd be consciously thinking about that.

And is there a possibility that 'Companions' could theoretically be anyone from the public? The main benefit being promoting intergenerational connection. Or is the aim of the app more peer companionship?

I'll certainly keep the wording in mind. Also feel free to pull me up if I'm using any words that aren't ideal.

**Comment by brylie** [comment]
> And is there a possibility that 'Companions' could theoretically be anyone from the public? The main benefit being promoting intergenerational connection. Or is the aim of the app more peer companionship?

Companions can be anyone pretty much, but primarily people who could use the app or be chaperoned. E.g., children wouldn't be primary users but might participate in intergenerational activities. 

It has also been suggested that the app could publish a list of people who need companionship and allow people to volunteer, but that suggestion would lead to a lot of considerations around privacy and safety. So for now, the app is focused around facilitating activities among a group of people who know one another (such as family, friends, and professional caregivers) who coordinate companionship activities centered around a single person (such as a family member).

The app would support a more peer-to-peer companionship model, such as a hobby group, but we need to pick a primary focus (currently a hub-and-spoke group model) and then pivot (to peer-to-peer group model) if/when the need arises.
