### ISSUE TITLE
Add test-coverage report to continuous integration pipeline

### ISSUE THREAD

**Issue by brylie** [CompanionshipCare/companionship-care#62]
We are currently using CodeClimate for quality review in our pull requests. CodeClimate can monitor test coverage if we [configure our project](https://docs.codeclimate.com/docs/configuring-test-coverage) correctly.

## Task

- [ ] enable project test coverage auditing with [coverage.py](https://coverage.readthedocs.io/)
- [ ] configure the necessary environment variable for CodeClimate "reporter ID" (done by. @brylie)
- [ ] follow the CodeClimate [instructions for setting up GitHub Actions to generate a coverage report](https://docs.codeclimate.com/docs/github-actions-test-coverage) - with adaptations for Python

## Example configuration

Something similar to the following may be all that is needed to enable test reporting in our project.

```yaml
coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: '3.10'
    - run: poetry install
    - run: coverage run -m pytest
```
